[bastion]
130.193.37.57

[webservers]
10.0.1.11
10.0.2.33

[databases]
10.0.1.30
[webservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@130.193.37.57"'
[databases:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q user@130.193.37.57"'
